### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by reyansh8104** [lord-cyclone100/pokedex#14]
Addition of dark mode to enhance user experience.

**Comment by reyansh8104** [comment]
@lord-cyclone100 Please assign me this issue under hacktoberfest.

**Comment by lord-cyclone100** [comment]
Sure @reyansh8104 gr8 idea!!!
go ahead.
If u haven't forked the repo, then pls do so and then make ur contribution
If u have alsready forked, make sure to sync our fork, git pull and then make your enhancements.

**Comment by lord-cyclone100** [comment]
one thing @reyansh8104 ....
it would be great if the toggle switch was a master ball so some sort of a variety of pokeball

**Comment by reyansh8104** [comment]
@lord-cyclone100 Okay

**Comment by Ayu10x** [comment]
I have made changes and made a PR please review it.

**Comment by lord-cyclone100** [comment]
> I have made changes and made a PR please review it.

@Ayu10x 
This issue is already assigned to @reyansh8104 
Pls follow the rules of open source contributions. You should not raise PRs without raising an issue first. If you want to work on a new enhancement or fix a bug then raise an issue. If you wish to work on an existing issue raised by others, then you must comment on that issue and wait until the current person gives up or crosses the deadline.
This is based on first come first serve basis.
Meanwhile you can check for other enhancements or find bugs in the project which no one before has pointed out and raise an issue.

**Comment by lord-cyclone100** [comment]
@reyansh8104 
If you are working on the issue, you have time till 25th October.

**Comment by lord-cyclone100** [comment]
@reyansh8104 
how is the progress?

**Comment by lord-cyclone100** [comment]
@Ayu10x 
If u like u can work on this issue

**Comment by lord-cyclone100** [comment]
@reyansh8104 
I have unassigned you because u did not turn in in time
